# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(900, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Logos/logo5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.Headline = QtWidgets.QLabel(self.centralwidget)
        self.Headline.setGeometry(QtCore.QRect(350, 40, 611, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Headline.setFont(font)
        self.Headline.setAlignment(QtCore.Qt.AlignCenter)
        self.Headline.setObjectName("Headline")
        self.static_native_name = QtWidgets.QLabel(self.centralwidget)
        self.static_native_name.setGeometry(QtCore.QRect(350, 130, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.static_native_name.setFont(font)
        self.static_native_name.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.static_native_name.setObjectName("static_native_name")
        self.static_en_name = QtWidgets.QLabel(self.centralwidget)
        self.static_en_name.setGeometry(QtCore.QRect(350, 160, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.static_en_name.setFont(font)
        self.static_en_name.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.static_en_name.setObjectName("static_en_name")
        self.static_date_issued = QtWidgets.QLabel(self.centralwidget)
        self.static_date_issued.setGeometry(QtCore.QRect(350, 190, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.static_date_issued.setFont(font)
        self.static_date_issued.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.static_date_issued.setObjectName("static_date_issued")
        self.static_valid_until = QtWidgets.QLabel(self.centralwidget)
        self.static_valid_until.setGeometry(QtCore.QRect(350, 220, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.static_valid_until.setFont(font)
        self.static_valid_until.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.static_valid_until.setObjectName("static_valid_until")
        self.static_cert_id = QtWidgets.QLabel(self.centralwidget)
        self.static_cert_id.setGeometry(QtCore.QRect(350, 250, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.static_cert_id.setFont(font)
        self.static_cert_id.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.static_cert_id.setObjectName("static_cert_id")
        self.static_CO = QtWidgets.QLabel(self.centralwidget)
        self.static_CO.setGeometry(QtCore.QRect(350, 280, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.static_CO.setFont(font)
        self.static_CO.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.static_CO.setObjectName("static_CO")
        self.placeholder_native_name = QtWidgets.QLabel(self.centralwidget)
        self.placeholder_native_name.setGeometry(QtCore.QRect(550, 130, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.placeholder_native_name.setFont(font)
        self.placeholder_native_name.setText("")
        self.placeholder_native_name.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.placeholder_native_name.setObjectName("placeholder_native_name")
        self.placeholder_en_name = QtWidgets.QLabel(self.centralwidget)
        self.placeholder_en_name.setGeometry(QtCore.QRect(550, 160, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.placeholder_en_name.setFont(font)
        self.placeholder_en_name.setText("")
        self.placeholder_en_name.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.placeholder_en_name.setObjectName("placeholder_en_name")
        self.placeholder_date_issued = QtWidgets.QLabel(self.centralwidget)
        self.placeholder_date_issued.setGeometry(QtCore.QRect(550, 190, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.placeholder_date_issued.setFont(font)
        self.placeholder_date_issued.setText("")
        self.placeholder_date_issued.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.placeholder_date_issued.setObjectName("placeholder_date_issued")
        self.placeholder_valid_until = QtWidgets.QLabel(self.centralwidget)
        self.placeholder_valid_until.setGeometry(QtCore.QRect(550, 220, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.placeholder_valid_until.setFont(font)
        self.placeholder_valid_until.setText("")
        self.placeholder_valid_until.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.placeholder_valid_until.setObjectName("placeholder_valid_until")
        self.placeholder_CO = QtWidgets.QLabel(self.centralwidget)
        self.placeholder_CO.setGeometry(QtCore.QRect(550, 280, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.placeholder_CO.setFont(font)
        self.placeholder_CO.setText("")
        self.placeholder_CO.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.placeholder_CO.setObjectName("placeholder_CO")
        self.placeholder_cert_id = QtWidgets.QLabel(self.centralwidget)
        self.placeholder_cert_id.setGeometry(QtCore.QRect(550, 250, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.placeholder_cert_id.setFont(font)
        self.placeholder_cert_id.setText("")
        self.placeholder_cert_id.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.placeholder_cert_id.setObjectName("placeholder_cert_id")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 90, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.cert_type = QtWidgets.QLabel(self.centralwidget)
        self.cert_type.setGeometry(QtCore.QRect(350, 90, 611, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cert_type.setFont(font)
        self.cert_type.setText("")
        self.cert_type.setAlignment(QtCore.Qt.AlignCenter)
        self.cert_type.setObjectName("cert_type")
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.actionRestart = QtWidgets.QAction(Main)
        self.actionRestart.setObjectName("actionRestart")
        self.actionClose = QtWidgets.QAction(Main)
        self.actionClose.setObjectName("actionClose")
        self.actionValidity = QtWidgets.QAction(Main)
        self.actionValidity.setObjectName("actionValidity")
        self.actionPassword = QtWidgets.QAction(Main)
        self.actionPassword.setObjectName("actionPassword")
        self.actionHelp_doc = QtWidgets.QAction(Main)
        self.actionHelp_doc.setObjectName("actionHelp_doc")
        self.actionAbout = QtWidgets.QAction(Main)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionRestart)
        self.menuFile.addAction(self.actionClose)
        self.menuSettings.addAction(self.actionValidity)
        self.menuSettings.addAction(self.actionPassword)
        self.menuAbout.addAction(self.actionHelp_doc)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        # Adding the program version to the title
        verr = open("ver.ini", "r")  # Opens it in read mode
        ver = list(verr)             # Converting data to list
        ver = str(ver[0])            # Taking the first (and only) item and convert it to str
        verr.close()                 # Closing the file
        Main.setWindowTitle(_translate("Main", "Certificate Checker " + ver))
        self.Headline.setText(_translate("Main", "EU DIGITAL COVID CERTIFICATE\n" "ЦИФРОВ COVID СЕРТИФИКАТ НА ЕС\n" ""))
        self.static_native_name.setText(_translate("Main", "Native Name:"))
        self.static_en_name.setText(_translate("Main", "EN Name:"))
        self.static_date_issued.setText(_translate("Main", "Date Issued:"))
        self.static_valid_until.setText(_translate("Main", "Valid until:"))
        self.static_cert_id.setText(_translate("Main", "Unique Certificate Identifier:"))
        self.static_CO.setText(_translate("Main", "Country:"))
        self.menuFile.setTitle(_translate("Main", "File"))
        self.menuSettings.setTitle(_translate("Main", "Settings"))
        self.menuAbout.setTitle(_translate("Main", "Help"))
        self.actionRestart.setText(_translate("Main", "Restart"))
        self.actionClose.setText(_translate("Main", "Close"))
        self.actionValidity.setText(_translate("Main", "Validity"))
        self.actionPassword.setText(_translate("Main", "Password"))
        self.actionHelp_doc.setText(_translate("Main", "Help doc"))
        self.actionAbout.setText(_translate("Main", "About..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())

